---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: 
    active: subject
  application:
    name: lab4-subject
words: I,You,He,She,It
  
---
spring:
  profiles: 
    active: verb
  application:
    name: lab4-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: 
    active: article
  application:
    name: lab4-article
words: a,the

---
spring:
  profiles: 
    active: adjective
  application:
    name: lab4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: 
    active: noun
  application:
    name: lab4-noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
